name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: emscripten make
      run: docker run --rm -v $(pwd):$(pwd) --workdir=$(pwd) trzeci/emscripten:sdk-tag-1.37.6-64bit make ffmpeg-h264.js
