name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check current
      run: ls
    - name: emscripten make
      run: docker run --rm -v $(pwd):$(pwd) -u $(id -u):$(id -g) trzeci/emscripten:sdk-tag-1.37.6-64bit ls
